name = "rescue-card"
account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"
workers_dev = true

[[routes]]
pattern = "/*"
service = "rescue-card-worker" # This should match the 'name'

[build]
command = "npm install"

[build.upload]
main = "./src/index.js"
